### ISSUE TITLE
Graph partitioning-based query system doesn't support SPARQL functions which may take N arguments

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Query#24]
I tried to run the graph partitioning-based query system as exemplified in the [SANSA-Examples](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/query/GraphQuery.scala) repository. The query I tried to execute is

```sparql
SELECT DISTINCT  ?s
WHERE
  { ?s   <http://www.specialprivacy.eu/langs/splog#logEntryContent>  ?s0 .
    ?s0  <http://www.specialprivacy.eu/langs/usage-policy#hasData>  ?allSuperClassesVar1 ;
         <http://www.specialprivacy.eu/langs/usage-policy#hasPurpose>  <http://www.specialprivacy.eu/vocabs/purposes#Admin> ;
         <http://www.specialprivacy.eu/langs/usage-policy#hasRecipient>  <http://www.specialprivacy.eu/vocabs/recipients#Public> ;
         <http://www.specialprivacy.eu/langs/usage-policy#hasStorage>  <http://www.specialprivacy.eu/vocabs/locations#ThirdParty> .
    ?s   <http://www.specialprivacy.eu/langs/splog#dataSubject>  <http://www.example.com/users/433a4347-e2c7-4e07-a0fd-a054a62ba37f>
    FILTER(?allSuperClassesVar1 NOT IN (<http://www.specialprivacy.eu/vocabs/data#Activity>, <http://www.specialprivacy.eu/langs/usage-policy#AnyData>))
  }
```

And what I get is this stack trace

```
Exception in thread "main" java.lang.UnsupportedOperationException: Not support the expression of ExprFunctionN
	at net.sansa_stack.query.spark.graph.jena.ExprParser.visit(ExprParser.scala:72)
	at org.apache.jena.sparql.expr.ExprFunctionN.visit(ExprFunctionN.java:120)
	at org.apache.jena.sparql.algebra.walker.WalkerVisitor.visitExprFunction(WalkerVisitor.java:265)
	at org.apache.jena.sparql.algebra.walker.WalkerVisitor.visit(WalkerVisitor.java:252)
	at org.apache.jena.sparql.expr.ExprFunctionN.visit(ExprFunctionN.java:120)
	at org.apache.jena.sparql.algebra.walker.WalkerVisitor.walk(WalkerVisitor.java:91)
	at org.apache.jena.sparql.algebra.walker.Walker.walk$(Walker.java:104)
[...]
```

pointing to [this `match`-`case` expression](https://github.com/SANSA-Stack/SANSA-Query/blob/develop/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/graph/jena/resultOp/ResultFilter.scala#L21-L23) which explicitly restricts supported filters to `Expression`s (i.e. basically everything that takes only up to two arguments).

**Comment by GezimSejdiu** [comment]
Hi @patrickwestphal ,

many thanks for the issue. Unfortunately, graph-based query engine in SANSA doesn't support such SPARQL fragments (`IN` and `NOT IN` statements). 
We will try to support such a feature when we cover more SPARQL 1.1 functions in the future. 

Best regards,
